config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments

  devise_for :users

  resources :users, only: [:update, :show, :index]
  resources :posts, only: [:index] do
    resources :locations
    resources :people
    resources :period
    resources :comments, only: [:create, :destroy]
    post '/likes-count' => 'likes#likes_count', as: :likes_count
  end

  resources :posts, except: [:index] do
    resources :locations, only: [:create, :destroy]
    resources :people, only: [:create, :destroy]
    resources :period, only: [:create, :destroy]
  end

  resources :locations
  resources :people
  resources :periods

  get 'json/data'
  get 'welcome/index'
  get 'test' => 'welcome#test'
  get 'about' => 'welcome#about'
  get 'profile' => 'welcome#profile'
  post 'search' => 'search#results', :as => 'search'

    root to: 'welcome#index'


end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :locations
  accepts_nested_attributes_for :locations
  has_and_belongs_to_many :people
  accepts_nested_attributes_for :people
  has_and_belongs_to_many :periods
  accepts_nested_attributes_for :periods
  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments
  mount_uploader :image, ImageUploader

  default_scope { order('created_at DESC') }
  scope :tagged_by, lambda { |person|
    where('person.id IN ?', person_ids)
  }

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

  def likes_count
      likes.where(value: 1).count
  end

  def points
     likes.sum(:value)
  end

  def update_rank
       age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
       new_rank = points + age_in_days

       update_attribute(:rank, new_rank)
  end

  def create_like
   user.likes.create(value: 1, post: self)
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      post = Post.create(title: @title, body: @body)
      create_vote
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    unless user_signed_in?
      render 'logged_out_homepage', layout: 'logged_out' and return
    else
      @posts = Post.all.paginate(page: params[:page], per_page: 6)
      @locations = Location.all
      render 'posts/index', layout: 'application' and return
    end

  end

  def about
    unless user_signed_in?
      render 'logged_out_about', layout: 'logged_out' and return
    end
  end

  def search
    unless user_signed_in?
      render 'search', layout: 'logged_out' and return
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.haml
- content_for :main_content do
  %h1 The idea behind Volunteer Connect
  %p If you were a Peace Corps Volunteer in Guinea, you probably read or wrote a site journal about the village that you lived in.  It was probably written on paper and left at the site.  You might have written a blog about your experiences that were not shared with others who lived in that same site.  You might have heard of the legends of past volunteers or residents of your sites.
  %br/
  %p When I first arrived at my village in Lelouma in 1994, I was told that I was the first Peace Corps volunteer serving there.  After about a year, I met someone who thought there might have been a volunteer in the mid 1960's.  I developed a kinship to the people in Lelouma and absolute love of the area.  I explored the area intensely and each day discovered new features of the land that I didn't know about.  I found new waterfalls, new cliffs, new handmade bridges out of vine and twigs, small villages, interesting people, interesting history about the village, etc.  I always wanted to share the cool things that I learned to the volunteers who came after me (and before me).  I never did.  There is probably only a handful of people who would be interested in this information and I would love to learn how the area has changed.
  %br/
  %p This site will allow us to share this information.
  %br/
  %h1 Sharing of Information
  %p Part of the problem is that many existing web venues are trying to make money with users content.  This creates problems about sharing personal information that only a limited amount of people will  truly value and be touched.
  %br/
  %p This site is built by volunteers for volunteers and it's content will never be sold or be given to earn money.

  %br/
  %h1 Where we are right now
  %p At the moment, this is built specifically for Friends of Guinea and Guinea Peace Corps Volunteers.  Photos and text are welcome.  Links to video can be made but attaching videos won't be possible.  To see the content, you must be a member (which is free).
  %br/
  %h1 Spelling
  %p Since many languages are spoken in Guinea, some written and some not.  Spelling of villages and areas vary depending on languages.  For this site, there needs to be a consistency so make it easier to search.  If you see glaring spelling issues, please let us know but we will try to stick with one way to spell a village for consistency.
  %br/
  %h1 Designed and Developed
  %p By UX Dysart LLC (Lelouma 94-96)

- content_for :nav_content do
  %h1 About Volunteer Connect!

app/views/welcome/index.html.haml
- content_for :nav_content do
  %h1 Left Nav Content

- content_for :main_content do
  %br/
  .jumbotron
    %h1
      Volunteer Connect
    %h1
      Friends of Guinea
    %p
      A way to share your Guinea Peace Corps Volunteer experiences with others who have served in Guinea in the past 50 years.
      %br/
      = link_to "Sign In", new_user_session_path, class: 'btn btn-primary'
      or
      = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'
      today!

app/views/welcome/logged_out_about.html.haml
.container
  %h1 The idea behind Volunteer Connect
  %p If you were a Peace Corps Volunteer in Guinea, you probably read or wrote a site journal about the village that you lived in.  It was probably written on paper and left at the site.  You might have written a blog about your experiences that were not shared with others who lived in that same site.  You might have heard of the legends of past volunteers or residents of your sites.
  %br/
  %p When I first arrived at my village in Lelouma in 1994, I was told that I was the first Peace Corps volunteer serving there.  After about a year, I met someone who thought there might have been a volunteer in the mid 1960's.  I developed a kinship to the people in Lelouma and absolute love of the area.  I explored the area intensely and each day discovered new features of the land that I didn't know about.  I found new waterfalls, new cliffs, new handmade bridges out of vine and twigs, small villages, interesting people, interesting history about the village, etc.  I always wanted to share the cool things that I learned to the volunteers who came after me (and before me).  I never did.  There is probably only a handful of people who would be interested in this information and I would love to learn how the area has changed.
  %br/
  %p This site will allow us to share this information.
  %br/
  %h1 Sharing of Information
  %p Part of the problem is that many existing web venues are trying to make money with users content.  This creates problems about sharing personal information that only a limited amount of people will  truly value and be touched.
  %br/
  %p This site is built by volunteers for volunteers and it's content will never be sold or be given to earn money.

  %br/
  %h1 Where we are right now
  %p At the moment, this is built specifically for Friends of Guinea and Guinea Peace Corps Volunteers.  Photos and text are welcome.  Links to video can be made but attaching videos won't be possible.  To see the content, you must be a member (which is free).
  %br/
  %h1 Spelling
  %p Since many languages are spoken in Guinea, some written and some not.  Spelling of villages and areas vary depending on languages.  For this site, there needs to be a consistency so make it easier to search.  If you see glaring spelling issues, please let us know but we will try to stick with one way to spell a village for consistency.
  %br/
  %h1 Designed and Developed
  %p By UX Dysart LLC (Lelouma 94-96)

app/views/welcome/logged_out_homepage.html.haml
%br/
.jumbotron
  %h1 Volunteer Connect
  %h1 Friends of Guinea
  %p A way to share your Guinea Peace Corps Volunteer experiences with others who have served in Guinea in the past 50 years.

  %form.navbar-form.navbar-center{:role => "search"}
    %button.dropdown.btn.btn-default#search_menu_button
      %a.btn-default.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
        %span.btn.glyphicon.glyphicon-th-list
          %span.caret
      %ul.dropdown-menu{:role => "menu"}
        %li
          %a{:href => "#"} All
        %li
          %a{:href => "#"} Location
        %li
          %a{:href => "#"} Time Period
        %li.divider
        %li
          %a{:href => "#"} Keyword
    .form-group
      %input.form-control{:placeholder => "Search for people, villages, time periods, and much more..", :type => "text"}/
    = link_to '',search_path, class: 'btn btn-default glyphicon glyphicon-search', id:'search_button'

    %br/
    %br/
    = link_to "Log In", new_user_session_path, class: 'btn btn-primary'
    or
    = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'
    today!

app/views/welcome/profile.html.haml
- content_for :main_content do
  .row
    .col-md-8
      %h3 Edit personal information
      = form_for current_user do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control', placeholder: "Enter name", autofocus: true
        - if current_user.avatar?
          .form-group
            %p Current avatar
            = image_tag( current_user.avatar.profile.url )
        .form-group
          = f.label :avatar
          = f.file_field :avatar
          = f.hidden_field :avatar_cache
        = content_tag :div, class: 'form_group' do
          = f.label 'About Me'
          = f.text_area :aboutme, rows: 6, class: 'form-control', placeholder: "Enter a little about yourself, what are doing now, where do you live now?"
        %h4
          .row
            .col-md-4
              = f.label 'Choose villages that you lived in Guinea:', class:  'control-label'
              = select_tag('user[location_ids][]', options_from_collection_for_select(Location.all, 'id', 'name' ), {:class => 'location', :id => 'prefetchlocation',:multiple => true})
            .col-md-4
              = f.label 'Choose Years that you lived in Guinea', class: 'control-label'
              = select_tag('user[period_ids][]', options_from_collection_for_select(Period.all, :start, :show_year), {:id => 'prefetchperiod', :multiple => true})
            .col-md-4
              = f.select(:position, [['Math Teacher',1],['English Teacher', 2]])
        .form-group
          = f.submit "Update", name: 'profile_button', class: 'btn btn-success'

- content_for :nav_content do
  %h1 Edit your Profile
  %h3 This is viewed by all members
  - if current_user.avatar?
    .large-avatar-photo
      = image_tag(current_user.avatar.profile.url)
  -else
    %span.large-avatar.glyphicon.glyphicon-user
  %br/
  %br/
  = link_to 'Change Account Information', edit_user_registration_path, class: 'btn btn-info'
  %br/
  %h4
    = current_user.aboutme
  %h4
    = current_user.position

app/views/welcome/search.html.haml
%br/
.jumbotron
  %h1 Volunteer Connect
  %h1 Thanks for checking out Volunteer Connect!
  %p Thanks for checking us out.  To see member's posts or to search for villages, people or cohorts you must log in.
  %p You can set up an account for free!



  = link_to "Log In", new_user_session_path, class: 'btn btn-primary'
  or
  = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'
  today!


%table.center-table.table
  %h3{style: 'text-align: center;'} Our users have recently submitted posts about these villages!
  %thead
    %tr
      %th Village
      %th Time Period
  %tbody
    %tr
      %td Lelouma
      %td 1994
    %tr
      %td Kankan
      %td 2001
    %tr
      %td Kindia
      %td 2008

%br/
%br/