config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments

  devise_for :users

  resources :users, only: [:update, :show, :index]
  resources :posts, only: [:index] do
    resources :locations
    resources :people
    resources :period
    resources :comments, only: [:create, :destroy]
    post '/likes-count' => 'likes#likes_count', as: :likes_count
  end

  resources :posts, except: [:index] do
    resources :locations, only: [:create, :destroy]
    resources :people, only: [:create, :destroy]
    resources :period, only: [:create, :destroy]
  end

  resources :locations
  resources :people
  resources :periods

  get 'json/data'
  get 'welcome/index'
  get 'test' => 'welcome#test'
  get 'about' => 'welcome#about'
  get 'profile' => 'welcome#profile'
  post 'search' => 'search#results', :as => 'search'

    root to: 'welcome#index'


end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  mount_uploader :image, AvatarUploader
  belongs_to :post
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @post_attachments = PostAttachment.all
    respond_with(@post_attachments)
  end

  def show
    respond_with(@post_attachment)
  end

  def new
    @post_attachment = PostAttachment.new
    respond_with(@post_attachment)
  end

  def edit
  end

  def create
    @post_attachment = PostAttachment.new(post_attachment_params)
    @post_attachment.save
    respond_with(@post_attachment)
  end

  def update
    respond_to do |format|
       if @post_attachment.update(post_attachment_params)
         format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
       end
     end
  end

  def destroy
    @post_attachment.destroy
    respond_with(@post_attachment)
  end

  private
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :image)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.haml
= form_for @post_attachment do |f|
  - if @post_attachment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post_attachment.errors.count, "error")} prohibited this post_attachment from being saved:"
      %ul
        - @post_attachment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :post_id
    = f.number_field :post_id
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/post_attachments/edit.html.haml
- content_for :nav_content do

  %h1
    Edit Attachment for Post:


- content_for :main_content do
  %h1 Editing post_attachment

  = render 'form'

  = link_to 'Show', @post_attachment
  \|
  = link_to 'Back', post_attachments_path

app/views/post_attachments/index.html.haml
%h1 Listing post_attachments

%table
  %tr
    %th Post
    %th Image
    %th
    %th
    %th

  - @post_attachments.each do |post_attachment|
    %tr
      %td= post_attachment.post_id
      %td= post_attachment.image
      %td= link_to 'Show', post_attachment
      %td= link_to 'Edit', edit_post_attachment_path(post_attachment)
      %td= link_to 'Destroy', post_attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post attachment', new_post_attachment_path

app/views/post_attachments/new.html.haml
%h1 New post_attachment

= render 'form'

= link_to 'Back', post_attachments_path

app/views/post_attachments/show.html.haml
- content_for :nav_content do

  %h1
    Show Attachment for Post


- content_for :main_content do
  %p#notice= notice
  %p
    %b Post:
    = @post_attachment.post_id
  %p
    %b Image:
    = @post_attachment.image

  = link_to 'Edit', edit_post_attachment_path(@post_attachment)
  \|
  = link_to 'Back', post_attachments_path