config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments

  devise_for :users

  resources :users, only: [:update, :show, :index]
  resources :posts, only: [:index] do
    resources :locations
    resources :people
    resources :period
    resources :comments, only: [:create, :destroy]
    post '/likes-count' => 'likes#likes_count', as: :likes_count
  end

  resources :posts, except: [:index] do
    resources :locations, only: [:create, :destroy]
    resources :people, only: [:create, :destroy]
    resources :period, only: [:create, :destroy]
  end

  resources :locations
  resources :people
  resources :periods

  get 'json/data'
  get 'welcome/index'
  get 'test' => 'welcome#test'
  get 'about' => 'welcome#about'
  get 'profile' => 'welcome#profile'
  post 'search' => 'search#results', :as => 'search'

    root to: 'welcome#index'


end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :locations
  accepts_nested_attributes_for :locations
  has_and_belongs_to_many :people
  accepts_nested_attributes_for :people
  has_and_belongs_to_many :periods
  accepts_nested_attributes_for :periods
  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments
  mount_uploader :image, ImageUploader

  default_scope { order('created_at DESC') }
  scope :tagged_by, lambda { |person|
    where('person.id IN ?', person_ids)
  }

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

  def likes_count
      likes.where(value: 1).count
  end

  def points
     likes.sum(:value)
  end

  def update_rank
       age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
       new_rank = points + age_in_days

       update_attribute(:rank, new_rank)
  end

  def create_like
   user.likes.create(value: 1, post: self)
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      post = Post.create(title: @title, body: @body)
      create_vote
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.all.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.paginate(page: params[:page], per_page: 6)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_attachments = @post.post_attachments.all
    @location = Location.all
    @person = Person.all.joins(@post.user)
    @period = Period.all
    @comment = Comment.new
    authorize @post
  end

  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
    @location = Location.new
    @locations = Location.all
    @person = Person.new
    @people = Person.all.joins(current_user)
    @period = Period.new
    @periods = Period.all
    authorize @post
  end

  def create
    @post = current_user.posts.build(post_params)
    authorize @post
    if @post.save
      unless params[:post_attachments].nil?
        params[:post_attachments]['image'].each do |a|
            @post_attachment = @post.post_attachments.create!(:image => a, :post_id => @post.id)
         end
      end
      flash[:notice] = "Post was saved."
      redirect_to [@post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @locations = @post.locations
    @people = @post.people
    @period = @post.periods
    authorize @post

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def query
      q = params[:query]
      @locations = Location.search(name_cont: q).result
      @people = Person.search(name_cont: q).result

  end

  def secondquery
    @location = Location.find(params[:id])
    @person = Person.find(params[:search])
    @posts = @location.posts & @person.posts
  end


  def destroy
    @post = Post.find(params[:id])
    authorize @post
    title = @post.title
    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to posts_path
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :image_cache, :url_link, :location_ids => [], :person_ids => [], :period_ids => [], post_attachments_attributes: [:id, :post_id, :image])
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for [post] do |f|
  - if post.errors.any?
    .alert.alert-danger
      %h4
        There are #{pluralize(post.errors.count, "error")}.
      %ul
        - post.errors.full_messages.each do |msg|
          %li= msg
  = content_tag :div, class: 'form_group' do
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Enter post title"
  = content_tag :div, class: 'form_group' do
    = f.label :body
    = f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body"
  .form-group
    = f.label 'Link to Webpage'
    = f.url_field 'url_link'

  .field
    = f.label :image
    %br/
    = f.file_field :image, :multiple => true, name: "post_attachments[image][]"

  - unless post.post_attachments.first.nil?
    - post.post_attachments.each do |p|
      = image_tag p.image_url
      -# = link_to "Edit Attachment", edit_post_attachment_path(p)

  .row
    .col-md-4
      .form-group
        = link_to 'Create a new Location', new_location_path, :class => 'btn btn-primary'
      .form-group
        = f.label 'Choose Locations', class: 'control-label'
        = select_tag('post[location_ids][]', options_from_collection_for_select(Location.all, 'id', 'name' ), {:class => 'location', :id => 'prefetchlocation',:multiple => true, :style => "display: none;"})
    .col-md-4
      .form-group
        = link_to 'Create a new Person', new_person_path, :class => 'btn btn-primary'
      .form-group
        = f.label 'Choose People', class: 'control-label'
        = select_tag('post[person_ids][]', options_from_collection_for_select(Person.all, 'id', 'name' ), {:id => 'prefetchpeople',:multiple => true})

    .col-md-4
      .form-group
        = link_to 'Create a new Date', new_period_path, :class => 'btn btn-primary'
      .form-group
        = f.label 'Choose Date', class: 'control-label'
        = select_tag('post[period_ids][]', options_from_collection_for_select(Period.all, :start, :show_year), {:id => 'prefetchperiod', :multiple => true})


  .form-group
    = link_to "Cancel", :back, class: 'btn btn-default'
    = f.submit "Save", class: 'btn btn-success'



  -# .dropdown
  -#   %button.btn.btn-default#dropdownLocation.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
  -#     %span#location_choice
  -#       Locations
  -#     %span.caret
  -#   %ul.dropdown-menu{"aria-labelledby" => "dropdownLocation", :role => "menu"}
  -#     - @locations.each do |location|
  -#       %li{:role => "presentation"}
  -#         %a{:id => location.id, :href => "#", :role => "menuitem", :tabindex => "-1"}
  -#           =location.name

app/views/posts/_post.html.haml
.media
  .media-body
    %h3.media-heading
      = link_to (post.title), [post]
    %p
      = post.body
      %small
      = image_tag(post.user.avatar.small.url) if post.user.avatar?
      submitted #{time_ago_in_words(post.created_at)} ago by
      = link_to post.user.name, post.user.person
      %br/
      %br/
      .owl-carousel
        - unless post.post_attachments.first.nil?
          - post.post_attachments.each do |p|
            = image_tag p.image_url
            -# = link_to "Edit Attachment", edit_post_attachment_path(p)
      .row
        .col-md-6.fill
          - unless post.post_attachments.first.nil?
            = image_tag post.post_attachments.first.image_url
        .col-md-6
          %img{:src => "https://maps.googleapis.com/maps/api/staticmap?&zoom=7&size=400x400&markers=color:blue%7Clabel:A%7C#{post.locations.first.latitude},#{post.locations.first.longitude}"}
      = link_to post.url_link, post.url_link if post.url_link?
    %h4
      Tags
    .row
      .col-md-4
        Locations:
        - post.locations.each do |location|
          =render partial: 'locations/location', locals: {location: location}
      .col-md-4
        People:
        - post.people.each do |person|
          =render partial: 'people/person', locals: {person: person}
      .col-md-4
        Date:
        - post.periods.each do |period|
          =render partial: 'periods/period', locals: {period: period}
    %h4
      = render partial: 'likes/like', locals: {post: post}
      Comments:
    .js-comments
      - post.comments.each do |comment|
        =render partial: 'comments/comment', locals: {comment: comment}

app/views/posts/edit.html.haml
- content_for :nav_content do
  %h1 Edit this Post

- content_for :main_content do
  = render partial: 'form', locals: { post: @post }

app/views/posts/index.html.haml
- content_for :nav_content do
  %h1 Left Nav Content

- content_for :main_content do
  - @posts.each do |post|
    = render partial: 'posts/post', locals: {post: post}

  .text-center
    -# = will_paginate @posts

app/views/posts/new.html.haml
- content_for :nav_content do
  %h1 Add a New Post

- content_for :main_content do

  - @post.locations.each do |location|
    =render partial: 'locations/location', locals: {location: location}


  = render partial: 'form', locals: { post: @post }

app/views/posts/photo.js.erb
$('.owl-carousel').click(function () {
  ('fill').replace('<%= escape_javascript(= image_tag post.post_attachments.next.image_url) %>");
  <% else %>')
}

})

<% if @location.valid?  %>
$('.js-locations').prepend("<%= escape_javascript(render(@location)) %>");
$('.new-locations').html("<%= escape_javascript(render partial: 'locations/form', locals: { post: @post, location: @new_location }) %>");
<% else %>
$('.new-locations').html("<%= escape_javascript(render partial: 'locations/form', locals: { post: @post, location: @location }) %>");
<% end %>

app/views/posts/show.html.haml
- content_for :nav_content do
  %h1
    =@post.title

- content_for :main_content do
  .row
    .col-md-10
      = render partial: 'post', locals: { post: @post }

  .new-comment
    = render partial: 'comments/form', locals: {post: @post, comment: @comment}



    .col-md-2
      - if policy(@post).edit?
        = link_to "Edit", edit_post_path( @post), class: 'btn btn-success'
      - if policy(@post).destroy?
        = link_to "Delete Post", [@post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' }