config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments

  devise_for :users

  resources :users, only: [:update, :show, :index]
  resources :posts, only: [:index] do
    resources :locations
    resources :people
    resources :period
    resources :comments, only: [:create, :destroy]
    post '/likes-count' => 'likes#likes_count', as: :likes_count
  end

  resources :posts, except: [:index] do
    resources :locations, only: [:create, :destroy]
    resources :people, only: [:create, :destroy]
    resources :period, only: [:create, :destroy]
  end

  resources :locations
  resources :people
  resources :periods

  get 'json/data'
  get 'welcome/index'
  get 'test' => 'welcome#test'
  get 'about' => 'welcome#about'
  get 'profile' => 'welcome#profile'
  post 'search' => 'search#results', :as => 'search'

    root to: 'welcome#index'


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_and_belongs_to_many :posts

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  respond_to :html, :js
  def destroy
    @post = Post.find(params[:post_id])
    @location = Location.find(params[:id])
    authorize @location

    if @location.destroy
      flash[:notice] = "Location was removed."
    else
      flash[:error] = "Location couldn't be deleted. Try again."
    end
  end

  def index
    if params[:search]
      @locations = Location.search(params[:search]).order("created_at DESC")
    else
      @locations = Location.order("name ASC")
    end
  end

  def show
    @location = Location.find(params[:id])

    if params[:filter]
      @person =  Person.find_by(name: params[:filter])
      @user = User.find_by(name: params[:filter])
      # This will show posts that have tags by this name and all the posts written by this name
      if @user.nil?
        @posts = @location.posts.joins(:people).where(people: {id: @person.id} )
        # @posts = (@person.posts & @location.posts)
      else
        @posts = @location.posts.joins(:people).where(people: {id: @person.id} ) + (@user.posts & @location.posts)
        # @posts = (@person.posts & @location.posts) + (@user.posts & @location.posts)
      end
      # @posts = Location.find(params[:id]).joins(:posts).tagged_with(@person)
    else
      @posts = @location.posts.paginate(page: params[:page], per_page: 6)
    end
    @locations = Location.all
    # This is code to get all the people to be unique  Something like
    # @people = @posts.joins(:people).uniq
    
    get_unique_people
    @unique_people = @pop.uniq




    @comment = Comment.new
    authorize @location
  end

  def edit
    @post = Post.find(params[:post_id])
    @location = Location.find(params[:id])
    authorize @location
  end

  def new
    @location = Location.new
    authorize @location
  end


  def create
    @location = Location.all.build(location_params)
    @new_location = Location.new
    authorize @location

    if @location.save
      flash[:notice] = "Location was saved."
      redirect_to new_post_path
    else
      flash[:error] = "There was an error saving the location. Please try again."
    end

  end

  private

  def location_params
    params.require(:location).permit(:name)
  end

  def get_unique_people
    @pop = []
    @posts.each do |post|
      post.people.each do |person|
        @pop.push(person)
      end
      @pop.push(post.user.person)
    end
  end

end

app/views/locations/_form.html.haml
= form_for [location], remote: true do |f|
  - if post.errors.any?
    .alert.alert-danger
      %h4
        There are #{pluralize(post.errors.count, "error")}.
      %ul
        - post.errors.full_messages.each do |msg|
          %li= msg
  %form.form-inline{:role => "form"}
    .form-group
      = f.label :"Enter New Location"
      .row
        .col-xs-6
          = f.text_field :name, class: 'form-control', placeholder: "Enter Location"
        .col-xs-2
          = f.submit "Save Location", class: 'btn btn-default'
          = submit_tag "Save Location", location.id, @post.locations.include?(location), class: 'btn btn-default'
        .col-xs-4


.dropdown
  %button.btn.btn-default#dropdownLocation.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
    %span#location_choice
      Locations
    %span.caret
  %ul.dropdown-menu{"aria-labelledby" => "dropdownLocation", :role => "menu"}
    - @locations.each do |location|
      %li{:role => "presentation"}
        %a{:id => location.id, :href => "#", :role => "menuitem", :tabindex => "-1"}
          =location.name

app/views/locations/_location.html.haml
= content_tag :div, class: 'media', id: "location-#{location.id}" do
  .media-body
    %p
      = link_to location.name, location, class: 'tag label label-info'
      - if policy(location).destroy?
        | #{link_to "Remove Location", [location.post, location], method: :delete, remote: true}

app/views/locations/create.js.erb
<% if @location.valid?  %>
$('.js-locations').prepend("<%= escape_javascript(render(@location)) %>");
$('.new-locations').html("<%= escape_javascript(render partial: 'locations/form', locals: { post: @post, location: @new_location }) %>");
<% else %>
$('.new-locations').html("<%= escape_javascript(render partial: 'locations/form', locals: { post: @post, location: @location }) %>");
<% end %>

app/views/locations/index.html.haml
- content_for :nav_content do
  %h1 All Locations

- content_for :main_content do
  - @locations.each do |location|
    %p
      =link_to location.name, location

app/views/locations/new.html.haml
- content_for :nav_content do
  %h1 Add a New Location

- content_for :main_content do

  %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCWDYd8haZXygQBD-YxNDCuaxCakY8Ikh4"}

  .col-md-8
    #panel
      %input#address{:type => "textbox", :value => "Conakry, Guinea"}/
      %input{:id => 'find_location',:type => "button", :value => "Search"}/
    #panel-delete-markers
      %input{:id => 'delete_markers', :type => "button", :value => "Delete Markers"}/
    #map-canvas
    = form_for @location do |f|
      %form.form-inline{:role => "form"}
        .form-group
          = f.label :"Enter New Location"
          .row
            .col-md-6
              = f.text_field :name, class: 'form-control', placeholder: "Enter New Location"
            .col-md-3
              = f.submit "Save Location", class: 'btn btn-success'
            .col-md-3
              = link_to "Cancel", :back, class: 'btn btn-default'

  .col-md-4
    %table.table.table-hover
      %thead
        %tr
          %th Current Locations
      %tbody
        - Location.all.each do |location|
          %tr
            %td
              = location.name

app/views/locations/show.html.haml
- content_for :nav_content do
  = link_to @location.name, @location, class: 'tag label label-info'
  - if params[:filter]
    = link_to @person.name, @person, class: 'tag label label-info'
  %h1
    = @location.name
  - if params[:filter]
    %h3
      = @person.name


  .dropdown
    %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
      People
      %span.caret
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
      - @unique_people.each do |person|
        %li{:role => "presentation"}
          = link_to person.name, {:filter => person.name}
      -# - @posts.each do |post|
      -#   %li{:role => "presentation"}
      -#     = link_to post.user.person.name, {:filter => post.user.person.name}

  = form_tag(location_path(@location), method: :get, class: "navbar-form navbar-left", id: "prefetch", :role => "search") do
    = text_field_tag :filter, params[:filter], id: "search_side_bar", class: "typeahead", placeholder: "Search ."
    %button.btn.btn-default#search_button{:type => "submit"}
      %i.glyphicon.glyphicon-search


- content_for :main_content do
  .row
    .col-md-12
      - @posts.each do |post|
        = render partial: 'posts/post', locals: { post: post }
        .new-comment
          = render partial: 'comments/form', locals: {post: post, comment: @comment}
  -# = will_paginate @posts